# Generated by Django 3.0 on 2020-09-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=70)),
                ('game_description', models.TextField()),
                ('game_video', models.CharField(max_length=100)),
            ],
        ),
    ]
