# Generated by Django 3.0 on 2020-09-15 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_play_time', models.TimeField()),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('play_time', models.TimeField()),
                ('game_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_record', to='games.Game')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
