# Generated by Django 3.0 on 2020-10-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='play_Time',
            new_name='play_time',
        ),
    ]
